"""empty message

Revision ID: 02082f15a6e9
Revises: 867a4142c6e4
Create Date: 2020-01-04 09:22:20.886185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02082f15a6e9'
down_revision = '867a4142c6e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('user.id', sa.Integer(), nullable=True),
    sa.Column('post.id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post.id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user.id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collections')
    # ### end Alembic commands ###
