"""empty message

Revision ID: 6b7f404b8795
Revises: eb642400fe0f
Create Date: 2020-01-05 20:16:25.088221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7f404b8795'
down_revision = 'eb642400fe0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('comment_id', sa.String(length=20), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('comment_date', sa.DateTime(), nullable=True),
    sa.Column('comment_name', sa.String(length=30), nullable=True),
    sa.Column('comment_support', sa.Integer(), nullable=True),
    sa.Column('comment_oppose', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('comment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
