"""empty message

Revision ID: eb642400fe0f
Revises: 02082f15a6e9
Create Date: 2020-01-05 20:15:04.770508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb642400fe0f'
down_revision = '02082f15a6e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('article_id', sa.String(length=20), nullable=False),
    sa.Column('article_title', sa.String(length=100), nullable=False),
    sa.Column('article_text', sa.Text(), nullable=True),
    sa.Column('article_summary', sa.String(length=255), nullable=True),
    sa.Column('article_read_cnt', sa.Integer(), nullable=True),
    sa.Column('article_sc', sa.Integer(), nullable=True),
    sa.Column('article_pl', sa.Integer(), nullable=True),
    sa.Column('article_date', sa.DateTime(), nullable=True),
    sa.Column('article_url', sa.Text(), nullable=True),
    sa.Column('article_type', sa.String(length=10), nullable=True),
    sa.Column('article_author', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_table('commparam',
    sa.Column('param_name', sa.String(length=10), nullable=False),
    sa.Column('param_value', sa.Integer(), nullable=True),
    sa.Column('param_text', sa.String(length=100), nullable=True),
    sa.Column('param_stat', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('param_name')
    )
    op.drop_index('ix_posts_rid', table_name='posts')
    op.drop_table('posts')
    op.drop_table('collections')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('user.id', sa.INTEGER(), nullable=True),
    sa.Column('post.id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['post.id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user.id'], ['users.id'], )
    )
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rid', sa.INTEGER(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('uid', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_posts_rid', 'posts', ['rid'], unique=False)
    op.drop_table('commparam')
    op.drop_table('article')
    # ### end Alembic commands ###
