"""empty message

Revision ID: f7454c7c8a08
Revises: e0f3844e1176
Create Date: 2020-01-03 09:19:55.478155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7454c7c8a08'
down_revision = 'e0f3844e1176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('icon', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'icon')
    # ### end Alembic commands ###
